name: Shams YouTube Monitor  # الاسم الجديد الذي سيظهر في القائمة

on:
  workflow_dispatch: # لتفعيل زر التشغيل اليدوي

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests
      - name: Run Bot
        run: python bot.py
