name: "1- Shams: Attendance Alert"

on:
  workflow_dispatch:

jobs:
  run-absent-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install Requirements
        run: pip install -r requirements.txt  # هذا هو السطر المضاف لتثبيت مكتبة التوقيت

      - name: Run Absent Bot
        run: python absent.py  # تشغيل ملف الغياب الجديد
