name: "2- Shams: YouTube Alert"

on:
  workflow_dispatch:

jobs:
  run-youtube-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install Requirements
        run: pip install -r requirements.txt  # ضروري لتشغيل البوت بتوقيت مصر

      - name: Run Youtube Bot
        run: python youtube.py  # تشغيل ملف اليوتيوب الجديد
